export { default as Ecommerce } from './Ecommerce'
export { default as Orders } from './Orders'
export { default as Employees } from './Employees'
export { default as Customers } from './Customers'
export { default as Calendar } from './Calendar'
export { default as Kanban } from './Kanban'